### ISSUE TITLE
battery icon depending on the battery percentage

### ISSUE THREAD

**Issue by GreyXor** [greshake/i3status-rust#1000]
Hello, font awesome offers these 5 icons
![image](https://user-images.githubusercontent.com/24626758/103888408-fa7a0b80-50e4-11eb-94ab-e3cbfd221050.png)

Here is the py3status configuration I was using and which allows this behavior
```
battery_level {
    blocks = ""
    charging_character = ""
    format = "{percent}%  {icon}"
    hide_seconds = true
    hide_when_full = true
    color_charging = '#6272a4'
    separator_block_width = 45
}
```
Is there an equivalent to `blocks = ""` with i3status-rust ?

it allows to display the battery icon depending on the battery percentage. rather than the default full battery icon.

Thank you

**Comment by GreyXor** [comment]
Ah well then it seems that is possible to override with 
```
"bat_charging" => " \u{f1e6} ",
"bat_discharging" => " \u{f242} ",
"bat_empty" => " \u{f244} ",
"bat_full" => " \u{f240} ",
"bat_half" => " \u{f242} ",
"bat_not_available" => " \u{f244} ",
"bat_quarter" => " \u{f243} ",
"bat_three_quarters" => " \u{f241} ",
```
This was not mentioned in the documentation. Then I think my problem is solved 👍🏼

**Comment by ammgws** [comment]
> font awesome offers these 5 icons

I couldn't check the icon codes since it was an image, but how are they different to the ones we already use?
https://github.com/greshake/i3status-rust/blob/a920c577669042bbf8d720c5af26355c166f6390/src/icons.rs#L88-L95

> ...seems that is possible to override with ... This was not mentioned in the documentation

Feel free to submit a PR updating the docs: https://github.com/greshake/i3status-rust/blob/master/themes.md#available-icon-overrides
