### ISSUE TITLE
Autolocate breaks the weather block

### ISSUE THREAD

**Issue by ram02z** [greshake/i3status-rust#1058]
When ``autolocate = true``, the weather block errors out.
![image](https://user-images.githubusercontent.com/59267627/107882530-c4992580-6ee1-11eb-96d4-36b5b946337b.png)

Tried using autolocate using city_id, place and coordinates and it fails every time. This behaviour is weird since if the ipapi call fails, the block should fall back to either city id or place.

Tested on Ubuntu 20.10 and version 0.14.5 of i3status-rs.
![image](https://user-images.githubusercontent.com/59267627/107882668-a849b880-6ee2-11eb-9b62-8707500115a8.png)

**Comment by ammgws** [comment]
Is this a regression?

**Comment by ram02z** [comment]
I have been using i3status-rs for over a month and the autolocate feature was working fine until I checked yesterday.

**Comment by ammgws** [comment]
This bisects to c0a0d3c23d014431745593fbee8646493173d99f from #1011 

Seems almost unrelated at first glance but I guess the geolocate service must be blocking our request based on the UserAgent.

**Comment by ammgws** [comment]
On further inspection, it looks like we are actually getting a proper response from the geolocation service. The issue is with the URL we generate which is quoting the city name, e.g.:

Bad
https://api.openweathermap.org/data/2.5/weather?q=\"Melbourne\"&appid=APIKEY&units=metric"

Good
https://api.openweathermap.org/data/2.5/weather?q=Melbourne&appid=APIKEY&units=metric"

Incidentally if we comment out the line that sets the user agent, we get blocked by the geolocation service since they seem to be rate limiting based on the user agent?
