### ISSUE TITLE
Pacman block showing wrong output

### ISSUE THREAD

**Issue by epixinvites** [greshake/i3status-rust#1192]
I checked with `pacman -Syyu` and `yay -Syyu`, and it showed 0 updates, while the block shows that it has 2 pending updates. I remember you had to delete a folder or something in `/tmp` for it to force refresh but I forgot which folder.

**Comment by epixinvites** [comment]
Never mind it's a duplicate of #834

**Comment by ammgws** [comment]
I don't think we ever found out what was going on though.

**Comment by epixinvites** [comment]
Actually, well, you could include this in your block documentation for the pacman block:
If you ever face problems of the wrong update count, just run `sudo rm -rf /tmp/checkup-db-'yourusername'`

**Comment by ammgws** [comment]
It would be good to know the actual root cause though.

**Comment by MaxVerevkin** [comment]
Random question: why doesn't `pacman` block use `checkupdates`?

**Comment by ammgws** [comment]
I'm not sure, if there was a reason I cannot recall it at the moment. I thought it might be because our way means we can get away without using root, but after taking a look at `checkupdates` script contents it looks like it's basically doing the same thing we are doing, except we don't have stuff like `rm -f $CHECKUPDATES_DB/db.lck` (maybe we need it?).

**Comment by epixinvites** [comment]
probably you need it
