### ISSUE TITLE
System Tray Icons

### ISSUE THREAD

**Issue by barun108** [greshake/i3status-rust#1209]
Hi 

I have disabled system tray output from i3 config 
How can I let i3status-rust display some app icons like zoom, telegram etc. ?

**Comment by ammgws** [comment]
You need to re-enable the system great in i3 if you want it to show. All i3status-rust does is output JSON to i3bar using the format specified by i3. i3bar then parses that JSON and renders the text in the bar. The system tray icons ate a totally separate and unrelated thing. Other status bars that don't use i3bar might support tray icons by themselves (like waybar on sway), but that is because they are a totally separate program that takes the place of i3/swaybar
