### ISSUE TITLE
Treat missing network device as down

### ISSUE THREAD

**Issue by JP-Ellis** [greshake/i3status-rust#121]
Currently, the network block does not play very nicely with removable network devices.

For example, I have a USB Ethernet adapter and the associated device (in `/sys/class/net`) is only present if the adapter is plugged in.  When the adapter is not there, I get an error instead.

Do you think `hide_inactive` should treat absent devices as being inactive too?  Or perhaps a new `ignore_missing` flag should be added for this?

**Comment by greshake** [comment]
Hmmm..... I'd prefer a default which shows something like `eth0 not available` and an option like `hide_unavailable`

**Comment by crypdick** [comment]
I second this. Whenever my device is missing, my whole bar is replaced with an error, making my bar mostly unusable.

![ss4](https://user-images.githubusercontent.com/5415776/33861759-84339ed4-dead-11e7-92b6-998aa4dba8f7.png)

**Comment by atheriel** [comment]
The issue is that the configuration needs a way to distinguish between "I misspelled my network device name" and "this network device might not always be present". I still think it makes sense to error in the first case.

Other than that this should be an easy fix.

**Comment by bemeurer** [comment]
@atheriel It might be complicated to figure out whether a device's name was misspelled or not, specially network devices that, at least on Linux, tend to end up with weird names sometimes. Do you know if/what the naming is POSIX-defined?

**Comment by atheriel** [comment]
My understanding is that this naming scheme is a part of the sysfs interface, and it seems at least in practice a bit of a wild west. At any rate, I think that this is sufficiently annoying to users that we should do the nice thing instead of the correct thing and just display an "x"  if the device is missing -- similar to the recent change to the weather block -- I just haven't had much time to actually implement it.
