### ISSUE TITLE
[discussion] Splitting code into crates

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1257]
Should some (not `i3status-rust` specific) code be published as separated crates so that other projects (like `swaystatus` until it ports all the blocks) may reuse it?

Examples of such crates might be
- cpu/memory/network statistics
- brightness control
- battery statistics
- formatting

**Comment by ammgws** [comment]
I know it's probably frustrating at the moment with the two codebases but I still don't see those crates being used by anything other than us. In fact for everything but formatting there might already exist some crates which we purposely avoided using since they were simple enough to be implemented ourselves. Perhaps remi or another active contributor could chime in as well?
