### ISSUE TITLE
awesome icons broken after ttf-font-awesome update on Arch

### ISSUE THREAD

**Issue by bluehood** [greshake/i3status-rust#130]
As per the pacman logs below, `ttf-font-awesome` was updated by pacman on the 29th of December,
which resulted in i3status-rust looking like this:

![image](https://user-images.githubusercontent.com/10999034/34487256-db2f7bcc-efd3-11e7-832a-33cbad77449b.png)

As you can see icons do not display properly anymore. removing `i3status-rust-git` and re-installing from AUR did not fix the issue.

Relevant snippet of pacman logs:
```
[2017-12-29 17:12] [PACMAN] Running 'pacman -Syu'                                                                       
[2017-12-29 17:12] [PACMAN] synchronizing package lists                                                                 
[2017-12-29 17:13] [PACMAN] starting full system upgrade                                                                
[2017-12-29 17:22] [ALPM] transaction started                                                                           
[2017-12-29 17:22] [ALPM] upgraded docker (1:17.11.0-1 -> 1:17.12.0-1)                                                  
[2017-12-29 17:22] [ALPM] upgraded mesa (17.3.0-2 -> 17.3.1-2)                                                          
[2017-12-29 17:22] [ALPM] upgraded firefox (57.0.2-1 -> 57.0.3-1)                                                       
[2017-12-29 17:22] [ALPM] upgraded lib32-mesa (17.3.0-2 -> 17.3.1-2)                                                    
[2017-12-29 17:22] [ALPM] upgraded numactl (2.0.11-1 -> 2.0.11-2)                                                       
[2017-12-29 17:22] [ALPM] upgraded ttf-font-awesome (4.7.0-5 -> 5.0.2-1)                                                
[2017-12-29 17:22] [ALPM] upgraded xorg-server-common (1.19.5-1 -> 1.19.6-2)                                            
[2017-12-29 17:22] [ALPM] upgraded xorg-server (1.19.5-1 -> 1.19.6-2)                                                   
[2017-12-29 17:22] [ALPM] transaction completed                                                                         
[2017-12-29 17:22] [ALPM] running 'fontconfig.hook'...                                                                  
[2017-12-29 17:22] [ALPM] running 'gtk-update-icon-cache.hook'...                                                       
[2017-12-29 17:22] [ALPM] running 'systemd-sysusers.hook'...                                                            
[2017-12-29 17:22] [ALPM] running 'systemd-update.hook'...                                                              
[2017-12-29 17:22] [ALPM] running 'update-desktop-database.hook'...                                                     
[2017-12-29 17:22] [ALPM] running 'xorg-mkfontdir.hook'... 
```

**Comment by atheriel** [comment]
This is due to the fact that version 4 and 5 of  `ttf-font-awesome` are incompatible (see e.g. [this issue](https://github.com/FortAwesome/Font-Awesome/issues/12017) for problems related to polybar). Try modifying your i3 config's font settings. If that doesn't work, my recommendation for now is to downgrade or use `ttf-font-awesome-4` from the AUR. That's what I'm doing at the moment, and it works just fine.

**Comment by bluehood** [comment]
Thank you for the quick response! If I understand correctly:
- there is no plan to migrate i3status-rust to the new version of ttf-font-awesome
- I should configure the bar to use ttf-font-awesome-4 from the AUR instead

I am unsure what you mean with "try modifying your i3 config's font settings. Currently it's
`font pango:DejaVu Sans Mono, Awesome 15` but I don't know how to switch it to version 4 -- any idea? 😅

**Comment by atheriel** [comment]
Since this is a font issue, it should be possible to modify your i3 config's settings to use the new font, e.g.

```
# with ttf-font-awesome-4:
font pango:DejaVu Sans Mono, FontAwesome 15
# with ttf-font-awesome:
font pango:DejaVu Sans Mono, FontAwesome5Free, FontAwesome5Brands 15
```
(You can see in the output of `fc-list | grep Awesome` that the name of the font has changed in version 5.) However, **this doesn't actually work for me**. I still get the same missing character artifacts.

This might be related to the fact that this Font Awesome does not have a blank space glyph, which was [an issue for the Siji font](https://github.com/stark/siji/issues/3) at some point, although I'm really just guessing now.

I'll continue to recommend downgrading. There is some [relevant discussion on Reddit](https://www.reddit.com/r/archlinux/comments/7n3uxw/font_awesome/) as well.

I'm not sure this is actually a problem with i3status-rust, since we can't modify any of our code to fix external font problems, but I'll leave the issue open for now. I'll very welcome to suggestions.

**Comment by bluehood** [comment]
> I'm not sure this is actually a problem with i3status-rust, since we can't modify any of our code to fix external font problems, but I'll leave the issue open for now. I'll very welcome to suggestions.

That is fair, but at least the dependency should be changed to `ttf-font-awesome-4` -- probably inform the AUR package maintainer if there is one.

**Comment by atheriel** [comment]
There's now some mention of this in the project README. I have no idea who is maintaining the AUR package, but perhaps @greshake will known.

**Comment by bluehood** [comment]
@mmetak thank you for the quick reply!
I did not experience any conflicts, the problem is that `i3status-rust` does not support `ttf-font-awesome` anymore, only `ttf-font-awesome-4`

**Comment by atheriel** [comment]
@mmetak Hijacking this a little, but I'll also point out that i3status-rust runs just fine under `sway`, so if you can indicate that the `sway` package satisfies the `i3` dependency that would be appreciated as well :smile:

**Comment by mmetak** [comment]
> EDIT:
> can confirm that the following one-liner solves the issue, if uninstalling ttf-font-awesome is an option:
> sudo pacman -Rns ttf-font-awesome && pacaur -S ttf-font-awesome-4

I was reffering to this part that you wrote. `ttf-font-awesome-4` package in AUR has `conflicts=('ttf-font-awesome')` when it doesn't conflict.  
They both have different file and font names so you can install them both at the same time, only have to adjust config file with proper names as @atheriel pointed out above.

@atheriel 
I just dropped i3-wm from depends and updated description to indicate that you can use it with i3bar or swaybar. That seems like simplest solution?

**Comment by bluehood** [comment]
@mmetak I see now, thanks! I went to the `ttf-font-awesome-4` aur page to comment and saw that you already did :)

However I am not sure how `i3` could decide which of the two icons to use if both packages were installed: the only line I have in my `i3/config` relative to `font-awesome`, which works for both version 4 and 5, is `font pango:DejaVu Sans Mono, Awesome 15`

**Comment by mmetak** [comment]
@bluehood 
```
$ fc-list | grep Awesome
/usr/share/fonts/TTF/fa-regular-400.ttf: Font Awesome 5 Free:style=Regular
/usr/share/fonts/TTF/fontawesome-webfont.ttf: FontAwesome:style=Regular
/usr/share/fonts/TTF/fa-solid-900.ttf: Font Awesome 5 Free:style=Solid
/usr/share/fonts/TTF/fa-brands-400.ttf: Font Awesome 5 Brands:style=Regular
```
I use `font pango:FontAwesome` for version 4 of font awesome and  `font pango:Font Awesome 5 Free` for 
 when I want version 5.

**Comment by bluehood** [comment]
fair enough :) as you can see I am very clumsy with fonts, sorry 😅

**Comment by atheriel** [comment]
It sounds like we should report this lack of conflict upstream to the `ttf-font-awesome-4` package, IMO.

@mmetak That works nicely, thank you.

**Comment by bluehood** [comment]
@atheriel it was reported [here](https://aur.archlinux.org/packages/ttf-font-awesome-4/) in the comments.

For what concerns me this issue can be closed: using `ttf-font-awesome-4` solves the problem with the icons, and both the README and the AUR package now report `ttf-font-awesome-4` as the optional dependency to get fancy icons :)

**Comment by y0ssar1an** [comment]
I'm using [`otf-font-awesome`](https://www.archlinux.org/packages/community/any/otf-font-awesome/), which is Font Awesome 5. Everything looks fine except the CPU icon is one of those weird glyphs.

i3status-rs version: 0.9

**Comment by atheriel** [comment]
I think insofar as we need to update the Unicode points used by the glyphs, that's probably true. I supported closing the issue primarily because this seemed to be more related to font specification in the i3 config than anything else. If we can isolate glyphs that have changed we should be able to make those changes relatively easily.

In the meantime you can change the icon used for the CPU in your config -- please let me know if that works.

**Comment by yaymukund** [comment]
In my case, the separator glyphs were bugging out because they require `powerline-fonts` by default. Solve by either installing `powerline-fonts` or changing [`icons.overrides`](https://github.com/greshake/i3status-rust/wiki/Theming-&-Icons#user-content-overwriting-themes-and-icon-sets).

**Before**
![Before screenshot](https://user-images.githubusercontent.com/590450/41977486-5dea5b68-7a17-11e8-80cb-b41d9a112d40.jpeg)

**After installing `powerline-fonts`**
![After screenshot](https://user-images.githubusercontent.com/590450/42022204-942d46ca-7ab4-11e8-9d73-515759a224d4.png)

**Comment by bemeurer** [comment]
I also don't think this should be closed, upgrading to using FontAwesome5 should at least be on the roadmap.

**Comment by atheriel** [comment]
@bemeurer What aspect of FontAwesome5 do we not support?

**Comment by bemeurer** [comment]
This is what my bar looks on Sway HEAD with the latest fontawesome (5.1.0) on Gentoo.
![foo](https://user-images.githubusercontent.com/7243783/49970269-9d003a00-fedf-11e8-921c-e36079a9bd13.jpg)
This is what it looks with fontawesome 4.7.0
![foo_2](https://user-images.githubusercontent.com/7243783/49970355-d638aa00-fedf-11e8-923f-7155471701db.jpg)

Some icons are missing on both, namely volume and brightness, but I think it's clear that with 5.1.0 it seems to work very poorly, font-wise.

**Comment by atheriel** [comment]
We will need a list of glyphs than have had their unicode value changed between version 4 and 5.

**Comment by glubsy** [comment]
This was reported [here](https://www.reddit.com/r/archlinux/comments/7n3uxw/font_awesome/) to be a problem with pango. 

Bug reports [here](https://gitlab.gnome.org/GNOME/pango/issues/273), and [here](https://gitlab.gnome.org/GNOME/pango/issues/265).

**Comment by atheriel** [comment]
Thanks for tracking that down, @glubsy.

**Comment by r00tman** [comment]
I think I found a workaround.

If a character doesn't belong to control, format, surrogate, or space separator categories, [pango](https://gitlab.gnome.org/GNOME/pango/issues/265#note_182806) treats it like a normal symbol. That means, if it is invisible, we can safely mix it with whitespaces. 

For example, there's one such symbol that works with current ttf-font-awesome: '\u{034f}' (COMBINING GRAPHEME JOINER). If you add one before the white space, the 0020 box goes away.

**Comment by prismspecs** [comment]
still broken

**Comment by MaxVerevkin** [comment]
@prismspecs What's broken?

**Comment by ammgws** [comment]
I assume using "awesome" instead of "awesome5" in the i3status-rust config
