### ISSUE TITLE
Mute icon with awesome5 is not the right one

### ISSUE THREAD

**Issue by welcoMattic** [greshake/i3status-rust#1399]
I've just installed i3status-rust (and it's the best bar software :heart: thanks for it!), but I catch a little thing with the muted icon:

Normal:
![2022-01-17_14-17_1](https://user-images.githubusercontent.com/773875/149776225-1d79da03-7316-465f-be94-989cde1c886d.png)

Muted:
![2022-01-17_14-17](https://user-images.githubusercontent.com/773875/149776221-8a7045c0-ba99-4e84-be1e-a49c3c921c3f.png)

I haven't change this icon in my configuration.

Here are the font package I have installed:

- ttf-font-awesome 5.15.4-1

Did I miss something?

**Comment by MaxVerevkin** [comment]
~~_Never mind, I forgot I had `icons_format` set to force NF._~~

What's your `i3`/`sway` config? Can you try setting the font to something like
```
    font pango: DejaVu Sans Mono, Font Awesome 5 Free 10
```
where instead of "DejaVu Sans Mono" you can place any font you like.

Please note that instead of "Font Awesome 5 Free" you can have something different. To list possible names run
```sh
fc-list | grep -i awesome
```

and to verify the name run
```sh
fc-match '<font name>'
```

**Comment by welcoMattic** [comment]
I had NerdFont installed, I've just removed them (not used).
And in my i3 config I had `font pango: DejaVu Sans Mono, FontAwesome 10` instead of `font pango: DejaVu Sans Mono, Font Awesome 5 Free 10`, it's fixed now. Thanks a lot!
