### ISSUE TITLE
Arrows are not smooth

### ISSUE THREAD

**Issue by Skycader** [greshake/i3status-rust#1400]
Hi, I'm using JetBrainMono (size 13) font in i3status-rust panel that allows to see that arrows aren't very smooth, however they aren't at any, it's just not that noticeable. Now, I have the same font for arrows in airline (vim/nvim) and they do look smooth, so I thought (maybe) it's the 
i3status-rust problem? Please check it out. 

Screenshot: https://ibb.co/ZcCCtJL

**Comment by MaxVerevkin** [comment]
That's not `i3status-rust`'s problem since it just streams JSON and nothing else.

I'm not sure whether it's JetBrainsMono's issue or `sway`'s or `pango`'s but I had the same issue with `sway` and I had to tweak the `height` option of the bar:
```
bar {
    height 18
    ...
}
```

### `height 20`
![image](https://user-images.githubusercontent.com/34583604/149808356-1fee53ae-f574-4b9f-94b5-886b3ecf5541.png)

### `height 18`
![image](https://user-images.githubusercontent.com/34583604/149808388-52902dcb-506d-4173-b40a-ff2d73b9fcea.png)

**Comment by GladOSkar** [comment]
All possible solutions have been discussed at length in these issues:

#94
#246

Unfortunately, there's nothing else we can do

**Comment by c02y** [comment]
I already gave up the arrow style long time ago since the bar height and font size will highly affect the arrows, even you make it perfect, when you switch your hardware, it will be broken again.

**Comment by MaxVerevkin** [comment]
Closing this as there is nothing we can do :/
