### ISSUE TITLE
Wayfire comatibility

### ISSUE THREAD

**Issue by Voklen** [greshake/i3status-rust#1483]
When on Wayfire, attempting to run `i3status-rs` doesn't show anything but still gives the terminal output of
```
{"version": 1, "click_events": true}
[
[{"full_text":"","color":"#002B36FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":" 273GB ","color":"#93A1A1FF","background":"#002B36FF","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#002B36FF","background":"#002B36FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"   10% ","color":"#93A1A1FF","background":"#002B36FF","name":"1","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#002B36FF","background":"#002B36FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"   3% ","color":"#93A1A1FF","background":"#002B36FF","name":"2","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#002B36FF","background":"#002B36FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  0.6 ","color":"#93A1A1FF","background":"#002B36FF","name":"3","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#002B36FF","background":"#002B36FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  92% ","color":"#93A1A1FF","background":"#002B36FF","name":"4","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#002B36FF","background":"#002B36FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  Wed 25/05 09:38 ","color":"#93A1A1FF","background":"#002B36FF","name":"5","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],
```
and then keeps printing out that last line every second (or just under that) with updated cpu usage and the like.
Both `wf-panel` and `waybar` create a bar at the top of the screen when ran but this doesn't happen here. If any more information is needed I can provide log files (if i3status-rust produces any). Thanks for any help you can give.

OS: Arch Linux x86_64
Kernel: 5.17.9-arch1-1

**Comment by MaxVerevkin** [comment]
Hi @Voklen

`i3status-rust` is not a status bar on itself, it is a program that generates JSON to be displayed by status bar that supports [i3bar protocol](https://i3wm.org/docs/i3bar-protocol.html). This includes `swaybar` for sway and `i3bar` for i3.

---

P.S. One of my personal projects, [i3bar-river](https://github.com/MaxVerevkin/i3bar-river), aims to bring i3bar-compatible status bar to other `wlroots`-based compositors such as `river`. I haven't tried `wayfire` yet, but since it is `wlroots`-based, `i3bar-river` should work just fine. If there are any `wayfire`-specific functionality that you would like to have in `i3bar-river`, feel free to open a feature request.

**Comment by Voklen** [comment]
Ah, that makes sense, thank you. I'll check it out then!

**Comment by Voklen** [comment]
@MaxVerevkin  Thanks, worked beautifully!
