### ISSUE TITLE
v0.30: kdeconnect fails if device not found

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1499]
v0.22
```sh
>i3status-rs test_kdeconnect.toml
{"version": 1, "click_events": true}
[
Icon bat_10 not found in your icons file. Please check NEWS.md
[{"full_text":"|","color":"#A9A9A9FF","background":"#000000FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":" PHONE Pixel4 EMP 0% NOTIF 1 ","color":"#DC322FFF","background":"#000000FF","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],
^C⏎
```

v0.30                                                                                                                       
```sh
>cargo run test_kdeconnect.toml
{"version": 1, "click_events": true}
[
[{"full_text":" ","name":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"Failed to read charge ","name":"0","markup":"pango"}],
```

**Comment by ammgws** [comment]
I think this is because in v0.22 we defaulted to `0` for the charge etc when the DBus method call failed in order to allow for missing devices, whereas that logic is not present in v0.30.

**Comment by GladOSkar** [comment]
For completeness' sake, i think this error also occurs if the device is connected but the charge can't be read, even if the charge isn't needed because it isn't used in the format string/block coloration

**Comment by ammgws** [comment]
So you can't even get the charge via `busctl --user get-property org.kde.kdeconnect /modules/kdeconnect/devices/yourdeviceid/battery org.kde.kdeconnect.device.battery charge`?

What version of kdeconnect are you using?

**Comment by ammgws** [comment]
What phone is it? Wonder if it's a bug with kdeconnect itself

**Comment by GladOSkar** [comment]
Moto G7, almost as stock as stock android gets. ¯\_(ツ)_/¯

**Comment by MaxVerevkin** [comment]
Does 7400195553777ec3fd9224b2c7aaf00b5a7305cc fix this issue?

**Comment by GladOSkar** [comment]
Yes, but as soon as the notification count drops to `0` i get

![image](https://user-images.githubusercontent.com/9497832/177040504-6f50f09c-3a59-4609-8be0-a965c800c5d2.png)

**Comment by MaxVerevkin** [comment]
Yeah, documentation is a bit out of sync with the code. Right now `notif_count` is not set if there are no notifications, because you might want to display something different than zero. IDK if it's practical.

Either docs or code should be changed. Not sure which behavior is better.

Sometimes I wish the config was in `lua` and the format was just a `function` (similar to `lualine` in `neovim`).

**Comment by GladOSkar** [comment]
Ahh makes sense. Sure why not, could be useful

**Comment by GladOSkar** [comment]
Another nit: After booting, the block always shows an the error `failed to get is_reachable` because the device isn't connected yet (no such path `/modules/kdeconnect/devices/7814dd5c9a77a7b2`) and then doesn't update once it does connect. Only when i reload using USR2 or reloading i3 it shows as normal.

**Comment by MaxVerevkin** [comment]
Seems resolved
