### ISSUE TITLE
Music block clipping issue

### ISSUE THREAD

**Issue by OneMoreByte** [greshake/i3status-rust#155]
On shorter song and artist combinations, I'm getting a weird block resizing issue where it leaves a chunk of deadspace in between the blocks (like in picture). 
![](https://i.imgur.com/Ur36nG4.png "error")

I'm not sure if it's a sway issue, so if anyone else could confirm this is an issue, please do.

**Comment by greshake** [comment]
Never seen that. But I've had similar problems with correct display in sway. Best check how sway renders the i3bar protocol. Or does it just use i3bar?

**Comment by ammgws** [comment]
I just checked and saw that mine is also like that. Didn't notice it until now.
From the screenshots below it doesn't seem to be just limited to shorter artists/titles...

Karnivool - We Are
![image](https://user-images.githubusercontent.com/20397027/36259716-75299078-12a2-11e8-94f1-3f38e02587d9.png)
The Avalanches - Tonight May Have to Last Me All My Life
![image](https://user-images.githubusercontent.com/20397027/36259725-802a48a0-12a2-11e8-97c5-c4c95323cdf1.png)
ZEEBRA - HIP　HOP　解放戦線　[Ft.　UZI]
![image](https://user-images.githubusercontent.com/20397027/36259734-8c400f44-12a2-11e8-9049-da3bebdb7fec.png)
スチャダラパー - ワープトンネル feat.ロボ宙&かせきさいだぁ
![image](https://user-images.githubusercontent.com/20397027/36259755-96aeaf80-12a2-11e8-838d-38e6da6011e4.png)

**Comment by OneMoreByte** [comment]
@greshake I'm not sure I'll have to look, I'm pretty sure they have their own implementation of i3bar with most if not all the functionality (?).

**Comment by greshake** [comment]
@ammgws Are you using i3 or sway?

**Comment by ammgws** [comment]
Sway.

**Comment by greshake** [comment]
Thing is, if the problem lies with RotatingTextWidget, it should be visible in i3. i3status-rust runs completely agnostic to the i3bar protocol renderer used

**Comment by atheriel** [comment]
E.g. according to swaybar's [relevant source code](https://github.com/swaywm/sway/blob/master/swaybar/render.c), it seems to support the `align`, `min_width`, `separator`, and `separator_min_width` parameters that are used by the widget. Maybe their precise behaviour is not the same as in i3?

**Comment by ammgws** [comment]
Could [this](https://github.com/swaywm/sway/pull/1636) be related?

**Comment by ammgws** [comment]
OK so the padding is gone if  `min_width` in [rotatingtext.rs](https://github.com/greshake/i3status-rust/blob/bb49eb575fede955a2facc98b050fe9105b85784/src/widgets/rotatingtext.rs#L129) from `240` to a lower number.

`min_width` = 240
![image](https://user-images.githubusercontent.com/20397027/45048027-b9f1c980-b0b5-11e8-985a-56ded6884bbb.png)

`min_width` = 40
![image](https://user-images.githubusercontent.com/20397027/45046802-3b475d00-b0b2-11e8-88ac-e409accf5172.png)

Also tried changing the align method from 'left' to 'right' or 'center' but it made no difference in terms of the gap.

Since only seems to occur in `sway` it must be a difference in how it's handling `min_width`.
[This](https://github.com/swaywm/sway/blob/309fcf23007a7c1b5c1c6da6b5ff7101312488cc/swaybar/render.c#L212-L219) seems to be the relevant section in `swaybar`, and [this](https://github.com/i3/i3/blob/6339427f017e1265a022e6537e16a8b4a921e52f/i3bar/src/xcb.c#L216-L233) is the i3 version.

**Comment by ammgws** [comment]
OK I believe I found the problem in sway's code.

Closing this and will report there instead.

**Comment by ammgws** [comment]
@OneMoreByte Could you please try with the latest sway-git and let me know if it fixes your issue?

**Comment by OneMoreByte** [comment]
It appears the original issue is fixed. Thanks @ammgws !
