### ISSUE TITLE
Custom block spacing/padding issues

### ISSUE THREAD

**Issue by arathunku** [greshake/i3status-rust#1582]
Hello there!

I've checked several issues regarding spacing but my search-fu is not good enough or there isn't an issue about it yet.

It looks like there's hard-coded empty space push:
https://github.com/greshake/i3status-rust/blob/e203adefbb68e39d81f7ddea135a7fcec58440ef/src/widget.rs

And then when icon is disabled:
https://github.com/greshake/i3status-rust/blob/e203adefbb68e39d81f7ddea135a7fcec58440ef/src/widget.rs#L125

It prevents the user of creating **very** minimal blocks, indistinguishable from tray icons. 

What I'm trying to do is to add few custom blocks (I love the new TOML configuration for click handling!), each outputting 1-3 emojis, displayed next to one another, each with its own cmd 

Currently, it looks like this:

![image](https://user-images.githubusercontent.com/749393/182024770-9a4d56e9-70e2-4ff4-a4aa-15902549bb10.png)

lock icon is custom block that may output 2 emojis, depending on the state

![image](https://user-images.githubusercontent.com/749393/182024937-babcbddc-af4e-453d-98a0-adcbdb1f7c66.png)

Notice the space, sometimes double, between blocks vs icons on the right from tray

What I'd ideally have looked like this:

![image](https://user-images.githubusercontent.com/749393/182024459-0d9e10bb-92b3-4172-9415-370c0374d4e5.png)

Or even less space if possible!!!

There's already formatting but I'm now sure how could it play nicely with custom blocks and those hard-coded(?) paddings within and around the block.

Looks like 0.3 is going to already have few breaking changes, so maybe it would be a good point to change some defaults / add configuration options. I'm happy to work on a PR to make those changes :)

Cheers,
Michal

**Comment by ammgws** [comment]
So I believe the double space comes from the leading space added between `SEPARATOR` and `BLOCK_TEXT` entries as shown in the json below:

```json
...
{"full_text":"SEPARATOR",...},
{"full_text":" ","name":"7",...},
{"full_text":"BLOCK TEXT ","name":"7",...},
{"full_text":"SEPARATOR",...},
```
(removed `color`, `background`, `separator`, `separator_block_width`, `markup` for clarity)

So no matter what you do in your config it's impossible to get rid of that space. I don't remember if it was always like this, it seems like if that space is necessary then we should just include it in the default block format string so it can be overridden. @MaxVerevkin Do you know why we have the space hardcoded atm?

**Comment by MaxVerevkin** [comment]
> Do you know why we have the space hardcoded atm?

I think this is the behavior of `v0.22` (and previous versions) as well. That is because we didn't want people to but put spaces manually, apparently. And then come the icons, which previously were defined with spaces around. Now those spaces can be disabled using `icons_format`.

We can try to remove all the hardcoded spacing and make it all configurable. And again, icons make it a harder. To be honest, I'm not against removing current idea of blocks having icons and instead just add `$icon` placeholder for every block.

Also, to make this work, we need a way to disable separators for specific blocks, we don't have that now, do we?

---

Related: #1539

**Comment by ammgws** [comment]
> To be honest, I'm not against removing current idea of blocks having icons and instead just add `$icon` placeholder for every block.

I think this is the way to go.

> Also, to make this work, we need a way to disable separators for specific blocks, we don't have that now, do we?

If it was as simple as adding `separator` as an option for `block.theme_overrides` that would be good...

**Comment by MaxVerevkin** [comment]
So I suppose the plan is:

- For every block, remove its icon and add `$icon` placeholder
- Remove code that handles icons from `widget.rs`
- Remove hardcoded spaces
- Provide a way to disable separators for specific blocks

Then instead of `format = "$value"` users would write something like `format = " $icon $value "`.

@arathunku would you like to try implementing this?

**Comment by arathunku** [comment]
Thank you for clarifications, the plan sounds good and not too complicated. I'll be on holiday until end of Aug so if nobody volunteers with help by then, I'll take this in September.

**Comment by arathunku** [comment]
Small status update: I'm working on it and got very promising results, but it will take some time to update examples and docs :smile: I'll submit a draft PR when it's ready for additional testing. I'm focusing on:

    * For every block, remove its icon and add $icon placeholder
    * Remove code that handles icons from widget.rs
    * Remove hardcoded spaces
