### ISSUE TITLE
Odd error: unknown field 'format', expected 'full' or 'short'

### ISSUE THREAD

**Issue by AManNeedsAMaid** [greshake/i3status-rust#1672]
My apologies if this is not a bug, I am not experienced with rust, but I've tried my best to look through the documentation and this error isn't making sense to me. 

Whenever I try to use i3status-rust (i.e. when I boot into or restart i3), it gives me an error on the top of my screen. I have attached a text file of the full error from a terminal when trying to run i3status-rs, as well as my config.toml (which I haven't really begun working on as the bar will not render) and the versions of all software I though was applicable.

I've tried so far:
Looking over the formatting docs, trying 'format = ', '[block.format] with 'full = ' and 'short = ', all of which return the same error. Deleting the last block results in the error being reported on new last block.

[versions.md](https://github.com/greshake/i3status-rust/files/10127109/versions.md)
[error-message.md](https://github.com/greshake/i3status-rust/files/10127110/error-message.md)
[config.toml.md](https://github.com/greshake/i3status-rust/files/10127125/config.toml.md)

Thank you for any help.

**Comment by GladOSkar** [comment]
The issue is not with the format of the `time` block, but your `disk_space` block.. The error message is a bit misleading here.

You can't use
```
[block.format]
format = " $icon root: $available.eng(2) "
```
only either
```
format = " $icon root: $available.eng(2) "
```
or
```
[block.format]
full = " $icon root: $available.eng(2) "
```

Additionally, `unit` is not a correct attribute anymore.

There is also an issue is in line 2 and 5, where you use `name = ` even though in v0.30, `name` has been removed.

Instead, you need
```
[theme]
theme = "plain"

[icons]
icons = "awesome"
```
as described in the breaking changes for v0.30 in `NEWS.md`.

The reason the errors say they're on Line 34 or so is most likely, that it looks for the correct attributes until the end of the file and once it doesn't find them there, fails there.

**Comment by AManNeedsAMaid** [comment]
Thanks so much, I couldn't wrap my head around the error message. Bar is beautiful and application works wonderfully, closing the issue now.
