### ISSUE TITLE
Time block does not reflect timezone changes

### ISSUE THREAD

**Issue by shazow** [greshake/i3status-rust#169]
To reproduce:

1. Change timezone, such as using  `timedatectl set-timezone "America/Los_Angeles"`
2. Wait for time block interval to update
3. Observe nothing happening. :(

Seems that the Rust mechanism we use to get the current time does not notice when the system's timezone changes. Right now I have to restart i3status for a new timezone to take effect, but this isn't ideal.

I'm not sure what a good solution is, but I'd be happy to give a shot at a fix if anyone has suggestions for how to approach this.

**Comment by greshake** [comment]
So, I tried this and it seems if you restart the bar (for example by restarting i3 in-place) the time is updated immediately. So unless you change timezones multiple times in a session this should be little to no annoyance, since it gets updated upon reboot etc. as well

**Comment by shazow** [comment]
Right, I also mentioned that restarting i3status-rust does the trick.

I tend to travel, so I show up in different timezones when I get off a plane. My timezone updates when I connect to new WiFi, but it's frustrating that my clock does not reflect that. The rest of my devices work fine (e.g. phone, etc).

**Comment by atheriel** [comment]
I would also appreciate if this could be added. I see that we use the `chrono` crate for grabbing the current time via `Local::now()`. Perhaps the place to look for timezone support is in that library.

**Comment by atheriel** [comment]
Upon further investigation, it seems that `chrono` uses the now-deprecated `time` crate for this particular call under the hood, which ends up calling into `libc::localtime_r()` at the bottom of the stack. Perhaps we are running into this issue because libc only checks the local timezone once per program/thread, but I'm just guessing. The [docs](https://linux.die.net/man/3/localtime_r) do not seem to mention these issues.

**Comment by progandy** [comment]
I think with glibc you have to call ```tzset()``` each time you want it to pick up a new timezone. If it is too expensive to do that on each call, then monitoring /etc/localtime or the file specified in the environment variable TZ (```TZ=:[filespec]```) is possible. If TZ is a fixed timezone string, then no checking has to be done since i3status-rust doesn't provide an API to change its TZ variable.

**Comment by derekdreery** [comment]
I filed a [chrono issue] about this.

[chrono issue]: https://github.com/chronotope/chrono/issues/272

**Comment by MaxVerevkin** [comment]
Fixed in 72a72845d0686ba802a131f16f7e2f184dfd4c7d
