### ISSUE TITLE
net: prioritize connected devices over disconnected when selecting an interface

### ISSUE THREAD

**Issue by okhsunrog** [greshake/i3status-rust#1758]
[[block]]
block = "net"
device = "^[we]"
format = " $icon {$ssid $signal_strength| $device} "

regex ^[we] is expected to match wlan0 and eth0. somehow is doesn't match wlan0, but regex ^[w] matches wlan0. what's wrong?

**Comment by cfsmp3** [comment]
What happens exactly, is doesn't find the device?

Have you tried replacing the regexp with the exact name just to make sure it works as expected then?

I just tried your (trivial) regexp and it works fine, so I suspect it's something else.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=25b43aaf539aa36cc039eb42cf8b58e7

**Comment by okhsunrog** [comment]
yes, it doesn't find the device. my device is wlan0. "^wlan0$" matches the device and "^[we]" does not match the device, it shows that there's no connection

**Comment by cfsmp3** [comment]
> yes, it doesn't find the device. my device is wlan0. "^wlan0$" matches the device and "^[we]" does not match the device, it shows that there's no connection

What about "^wlan0" (without $)? 

Could you try "^[we].*$" while we are at it?

**Comment by okhsunrog** [comment]
^wlan0 works
^[we].*$ doesn't

**Comment by okhsunrog** [comment]
that's really weird

**Comment by GladOSkar** [comment]
I'm pretty sure the `net` block only supports one interface per block. The block will find the first interface matching the regex, whether it's connected/active or not. In your case, `eth0` is probably always found first (likely because it comes first alphabetically). Your regex would only result in `wlan0` if the `eth0` interface disappeared (like e.g. a USB Ethernet adapter).

If your `eth0` interface is permanent, you'll need a second `net` block. You can make it look like they're one block by setting `missing_format = ""` on both, such that they disappear when not connected.

**Comment by MaxVerevkin** [comment]
> The block will find the first interface matching the regex, whether it's connected/active or not

Yes. But I guess prioritizing enabled interfaces makes a lot of sense.

**Comment by MaxVerevkin** [comment]
@okhsunrog can you test 2902e90?
