### ISSUE TITLE
pacman block v2 idea dump

### ISSUE THREAD

**Issue by matthiaskrgr** [greshake/i3status-rust#179]
instead of calling pacman in fakeroot env, I believe we can simply
1) use "checkupdates" to check for official package updates (does not require fakeroot)
this is nice because it seems to be shipped with pacman anyway
2) use "cower -du" to check for aur update.
would require cower to be installed
3) count total number of output lines for number of updates

alternatively we could display one number for aur updates and one for official updates.

**Comment by atheriel** [comment]
I am also in favour of moving to `checkupdates` for simplicity, but note that `checkupdates` itself is implemented using `fakeroot`, which I imagine is the rationale behind the original choice. Also, note that it is **not** part of `pacman`, but of `pacman-contrib` -- though that seems to be installed on Arch-based systems by default as well.

@keeslinp, since you appear to be the original author of the block, do you have any objection to moving to `checkupdates`? Or happen to remember what your original thinking was at the time?

**Comment by atheriel** [comment]
As a secondary issue: we should be careful about making use of `cower`. AUR package managers have come and gone at an alarming rate over the last few years, and I certainly do not want to be drawn into the particularly virulent discussion of these tools.

**Comment by yawpitch** [comment]
One additional note: `pacman-contrib` is NOT installed by default on Arch systems. The machine I'm working on currently is very little more than the minimal Arch install described in the wiki, and it's never been installed.

Also as @atheriel mentioned, `checkupdates` is using `fakeroot` internally ... it does use a slightly different command from the current block (`pacman -Qu` instead of `pacman -Su`), but basically we'd just be introducing another Arch package dependency to get to the same outcome.

**Comment by atheriel** [comment]
Ah, that's my mistake -- I'm on Manjaro, not Arch, and it seems to be installed by default. From discussion in #192 it looks like we are moving to `pacman -Qu` as well.

**Comment by keeslinp** [comment]
I don't have any problems with that change.
