### ISSUE TITLE
Add a new privacy indicator

### ISSUE THREAD

**Issue by emersion** [greshake/i3status-rust#1973]
Use PipeWire to figure out when the microphone, camera, or screen capture is in use.

Ref https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2840

**Comment by bim9262** [comment]
I've started work a privacy indicator. I checked my setup though and my camera doesn't appear to be used by pipewire (although I see it listed). Applications are using it directly (the webcam shows up in `v4l`).

Other drivers:

- [ ] `pipewire` (audio capture)
- [ ] `pipewire` (screen capture)
- [ ] `pipewire` (webcam)
- [ ] `pulseaudio` (audio capture)?

**Comment by emersion** [comment]
Note, more applications should move to PipeWire for camera as the ecosystem moves to libcamera. But yeah, it's still the early days.

**Comment by MaxVerevkin** [comment]
Is there something left not implemented in #1973?

**Comment by bim9262** [comment]
This issue was about pipewire monitoring. If someone wants to add another driver another issue can be opened.

**Comment by emersion** [comment]
Thank you for working on this!

**Comment by bim9262** [comment]
You're welcome, it was a fun block to work on

**Comment by kevenwyld** [comment]
I'm trying to use this (Because it's really cool!) however I noticed the docs say `pipewire Options (requires the pipewire feature to be enabled)`.  Unfortunately it doesn't mention which feature as far as I can tell and audio/screencapture don't seem to be working.  I read through the PR but I'm still not quite sure what I should be enabling or if these features should work like I'm expecting.  Is there additional documentation I should be looking at or does anyone here have any suggestions?

Thanks!

**Comment by MaxVerevkin** [comment]
@kevenwyld you have to compile with `-F pipewire` flag.

**Comment by kevenwyld** [comment]
> @kevenwyld you have to compile with `-F pipewire` flag.

That worked perfectly, thanks!
