### ISSUE TITLE
`bad event` when toggle `i3status-rust` for `focused_window` block

### ISSUE THREAD

**Issue by maximyurevich** [greshake/i3status-rust#1986]

**Comment by MaxVerevkin** [comment]
1. Can you provide more detailed steps to reproduce this?
2. You can click on the error to see a more detailed error message. Please post it too.

**Comment by tkapias** [comment]
I upgraded my cargo build from 33.1 to 33.2 today and now I get this "Bad Event" error in some cases when I bring a window from the scratchpad.

It happens when I use `"i3-msg -q '[id="xxx"]' move to workspace current, focus` with an id criteria or any other. 

It happen also when I use i3switcher or `i3-msg -q scratchpad show`.

The `unknown variant 'changed'` error:

![image](https://github.com/user-attachments/assets/60b6ddd2-54f4-4034-96b4-75de5902a337)

**Comment by tkapias** [comment]
I checked for i3 and the 'changed' state is [expected](https://github.com/i3/i3/blob/2746e0319b03a8a5a02b57a69b1fb47e0a9c22f1/docs/ipc#L479):

```
scratchpad_state (string)::
	Whether the window is not in the scratchpad ("none"), freshly moved to
	the scratchpad but not yet resized ("fresh") or moved to the scratchpad
	and resized ("changed").
```

## Solution

The bug comes from the cargo.lock for swayipc-types.

The version used is 1.3.2 but the 'changed' state for the scratchpad was introduced in [1.4.0 in september](https://github.com/JayceFayne/swayipc-rs/commit/11975da6d0011b175c92175c7e1c1de9b38d03f9).

Building without --locked works fine.

**Comment by lowlevl** [comment]
Hi there, just to inform you that this occurs on Manjaro with the latest `0.33.2` version of i3status-rs, maybe a new release fix release with the updated `swayipc-types` would be nice :)

Thanks.
