### ISSUE TITLE
When should we bump to 0.10?

### ISSUE THREAD

**Issue by atheriel** [greshake/i3status-rust#201]
By my reckoning, the last version change was 11 months ago, in commit 3710583. I think it's time we bumped the version to get stable users all the changes since that time.

@greshake, what outstanding work would you like to see done before this happens?

**Comment by barraponto** [comment]
I'm looking forward to the next release ever since #16 was fixed...

**Comment by Moredread** [comment]
A bump would be great, so I can update the package on NixOS :)

**Comment by greshake** [comment]
I was originally hoping to rewrite the whole program including blocks to a system working with async/await powered by a tokio core, but unforunately there are still important features missing that prevent such a migration (mainly borrowing in futures- which has been partially implemented now). I'm also super busy still which prevents me from cleaning up a lot... But in general, I'd like to get major parts of the internals cleaned up and rewritten before we bump the version. Updates in the last year were exclusively focused on the blocks and not on the core system itself. AUR users are already supplied with the latest version since they use the latest commit ID as version number, maybe this also works for NixOS?

**Comment by atheriel** [comment]
I'm supportive of more internal changes, but I do think we should try to have a vision for what exactly those changes should be. Can I ask what you have in mind?

**Comment by greshake** [comment]
These are the issues with the status quo I'm hoping to fix:
1.
Blocks that do lengthy I/O in the update function cause delays to display updates of other blocks because they run on the main thread to allow simpler resource sharing and access from the thread that renders the widgets. This is an issue with the pacman block for example (at least last time I checked)- every ten minutes or so, the bar hangs for a couple seconds while pacman is asked for updates. We have the option to do this in a seperate thread and ping the main thread when the results are available already, but it is very, very unergonomic and requires launching a thread, threadsafe memory structures like mutex for sharing results, and channels. All this could be done asynchronously on the main thread without blocking if we use async/await or futures. This saves resources, allows us to omit a lot of concurrency/resource locking overhead and can be implemented effortlessly once the main framework is using tokio. This also allows us to handle asynchronous events like mouse clicks etc. in an ergonomic way instead of awkwardly using a 'select'-equivalent channel wait funtion. 

2. More elegant rendering/caching
Right now, we still perform a lot of unnecessary memory copies and string operations on updates that may only mutate a single value. I'd like to rewrite the rendering of widgets s.t. anytime an update is made, as little resources as possible are used. While we are still more performant than all other bars I've tested except the C version of i3status, there is still some room for improvement. To achieve this in combination with the requirements of 1. I need to be able to handle references beyond future boundaries. Unfortunately, the current stable implementations impose an implicit 'static bound on all arguments and results of futures. This would lead to more memory operations and less efficiency, so for now I'm waiting for borrowing in futures :)

**Comment by jcgruenhage** [comment]
While always building from master is possible, having versioned releases (including git tags!) of this tool would be greatly appreciated. I'm currently packaging it for voidlinux, but it can't be merged into the main repository without a release + tag.

**Comment by jcgruenhage** [comment]
We've now had nearly two years since the last version bump, half of the commits in this project have been made since then. Can you please bump the version and tag it in the git repository?

**Comment by atheriel** [comment]
@jcgruenhage Despite being the more active maintainer, I don't feel I have the authority to do that against @greshake's wishes. Otherwise I would.

The reality is that we will have to wait.

**Comment by jcgruenhage** [comment]
Are the two things he listed nearly a year ago still not a thing? If those have been blocked for a year, and development has been progressing in other areas, continuing to wait doesn't seem logical to me. Those two also seem more like blockers for a 1.0, not for a 0.10.0. Considering that those two issues are also present in 0.9.0, releasing a 0.10.0 without those issues fixed doesn't seem wrong.

@greshake Please reconsider this. While other distros allow packaging master, there are also distros like voidlinux where only releases are packaged. Keeping with the current "no release until everything is fixed" strategy means that it's a major pita for some users to update this otherwise really nice application

**Comment by atheriel** [comment]
@jcgruenhage We're on the same side here, and making the same arguments.

**Comment by jcgruenhage** [comment]
Considering there's only been a single commit from @greshake in 2019 so far and no response here in 2 weeks, either just going through with a release or forking away and doing the release over there would be a good idea. I'm really thankful for the work done here by @greshake, but it doesn't look like this project is high up in their priorities right now.

**Comment by greshake** [comment]
Hey guys, I'm really sorry about my absence. I've been focused on my studies, work and thesis for the past year. I'll take a day or two this weekend and just spend it cleaning up in here. Lots of open issues, PRs and organization to be done. Special thanks to @atheriel and his amazing commitment to the project. I'm really happy so many people decided to contribute and I want to start giving back again. 

I'm sure we can start releasing tagged versions right away, too.

**Comment by greshake** [comment]
Oh and I don't very often look through the Github notifications anymore, but you can always ping me at development@kai-greshake.de.

**Comment by jcgruenhage** [comment]
@greshake that's great news, thank you!

**Comment by greshake** [comment]
I'm going to tag a release now. There is still a lot of outstanding work, but I'm not going to keep you waiting. We can always still release new versions :)

**Comment by jcgruenhage** [comment]
Awesome! Can you also tag that release in git?
