### ISSUE TITLE
Privacy indicator identifies pavucontrol as an audio capture

### ISSUE THREAD

**Issue by emersion** [greshake/i3status-rust#2070]
While pavucontrol is open, the privacy indicator indicates that audio is being captured, even though pavucontrol isn't really capturing any audio stream.

**Comment by bim9262** [comment]
You can add "PulseAudio Volume Control" to your `exclude_input`.
I think that adding it to the list of defaults would be ok since it's just using it to show levels.

Example connections while pavucontrol is open:
![image](https://github.com/user-attachments/assets/adee41fa-6504-4cb4-b529-1e3ca2b76e2e)

**Comment by emersion** [comment]
Hm, I see. So there is no way to make the difference between a client monitoring a stream, and a client actively capturing from a stream? I suppose pavucontrol indeed captures the streams to show the volume meters?

Sorry for the fuss then, and thanks for the hint!

**Comment by bim9262** [comment]
I'll try to dig through some metadata about the nodes or links, but as far as I recall there wasn't anything helpful to key off of.

You're welcome
