### ISSUE TITLE
Music block doesn't seem to honour max_width

### ISSUE THREAD

**Issue by SergeantBiggs** [greshake/i3status-rust#223]
I've just started using i3status-rust today and I noticed that the music player block always seems to take the same amount of space, even with "max_width" turned to a lower number. If I do that, it uses even less space from the block (scrolls more), but stays the same size overall. It this wanted?
![bug_i3status_rust](https://user-images.githubusercontent.com/19983492/43369701-b7b60754-9372-11e8-9d89-c60e1edd14da.png)

**Comment by ammgws** [comment]
Related to #155?

**Comment by SergeantBiggs** [comment]
No, doesn't seem like it since I use it, not sway

**Comment by ammgws** [comment]
Pretty sure it is due to [this line](https://github.com/greshake/i3status-rust/blob/bb49eb575fede955a2facc98b050fe9105b85784/src/widgets/rotatingtext.rs#L129) in `RotatingTextWidget` which tells i3 to set the minimum width of the block to 240 pixels. Where as the `max_width` setting for the music block is actually only used for setting the number of characters after which it will start to scroll, and not for setting the width fo the block ([see here](https://github.com/greshake/i3status-rust/blob/bb49eb575fede955a2facc98b050fe9105b85784/src/widgets/rotatingtext.rs#L63-L67).
(Even though the music block docs say "Max width of the block in characters, not including the buttons")

@greshake Is there a reason why the widget is hardcoded to 240 pixels?

**Comment by SergeantBiggs** [comment]
Yes it works now. Thank you!
