### ISSUE TITLE
Automatic discovery

### ISSUE THREAD

**Issue by mredaelli** [greshake/i3status-rust#241]
As a user of i3status I'm trying out i3status-rust. Very cool!
My only problem would be that I have my config files in a repository and I would like to have only one for all my machines.
With i3status it worked out of the box, because things like the network interface and the battery device where automatically discovered, and if they did not apply it was gracefully handled.

With i3status-rust I'm not sure how to handle it. If I put a battery block but there is no battery, I get an error.
For the network, I need to specify the interface, but that varies across PCs.

What would you recommend?

**Comment by GladOSkar** [comment]
The Battery thing is in progress, but automatically detecting the correct network interface would probably be complicated

**Comment by uinput** [comment]
Actually the best solution would be to have individual profiles for that. Just having blocks disappear because the software determines they cannot be displayed may lead to confusion on the user side. We need to have some way to explicitly allow the software to do that, so that people don't loose time figuring out why something is not displayed as they wish.

**Comment by atheriel** [comment]
@uinput is correct, the way forward is probably some sort of profile construction, as discussed in #85. Handling missing battery/network devices is also discussed in #145 and #121.

I'm going to close this as a duplicate. Feel free to reopen it if you think you're trying to make a new point.
