### ISSUE TITLE
[music] 5 empty spaces between title and pause icon

### ISSUE THREAD

**Issue by sebastianst** [greshake/i3status-rust#289]
My music block always shows ~5 empty spaces between the title and pause icon, even if it's a long, rotating title. My block config:
```
[[block]]
block = "music"
player = "spotify"
max_width = 36
buttons = ["play", "next"]
```

**Comment by sebastianst** [comment]
Also, the block is always `max_width` wide, even for shorter titles. Judging from the `max` in the property's name I assumed that the block would shrink for shorter titles.

**Comment by rhythmthief** [comment]
> Also, the block is always `max_width` wide, even for shorter titles. Judging from the `max` in the property's name I assumed that the block would shrink for shorter titles.

This. The block actually used to scale similarly to focused_window, but apparently something got broken a few months ago.

**Comment by ammgws** [comment]
The 5 empty spaces is probably due to the 'magic number' padding added in #250 to solve the 'jitter' as it scrolled. If you can find the cause of the jitter in the block logic somewhere then perhaps the padding could be removed, but I couldn't pinpoint it at the time.

The name `max_width` is misleading - it actually sets the minimum length of the block.
However, perhaps there could be an option for the block to shorten itself for those who want to reduce blank space.

**Comment by sebastianst** [comment]
I think it would be best to have a `width` field, which configures a static width. Then there could be two fields named `min_width` (default 0) and `max_width`, which set the boundaries for a dynamic width. If the whole text is longer than `width` or `max_width`, only then does scrolling kick in. Usage of static and dynamic width would, of course, be mutually exclusive.

I'll have a look at the scrolling logic, maybe I'll spot something ;)

**Comment by ammgws** [comment]
@sebastianst The 5 spaces should be gone after d4bbd096df6e0a5c917468c91a1931aaa2dbf802. Can you confirm?

**Comment by ammgws** [comment]
@sebastianst Sounds like #584

@sebastianst The 5 spaces are gone now.
