### ISSUE TITLE
rustfmt policy

### ISSUE THREAD

**Issue by kennylevinsen** [greshake/i3status-rust#340]
I believe it would be a good idea to consider a policy for requiring rustfmt or similar. This can be enforced through travis hooks or similar.

Such policy would make the code more consistent, and give fewer surprises for the few of us with auto-fmt'ing editors.

**Comment by atheriel** [comment]
This has come up a number of times before. As I [remarked at the time](https://github.com/greshake/i3status-rust/pull/174#issuecomment-384643728):

> [S]o far in practice we've only really been updating the format of code as it has actively been worked on, which is not a bad policy. I know this is results in ugly inconsistency, but it does have the advantage of preserving git history on line changes more clearly, and it is not unusual in open-source projects to favour this over style adherance.

That said, I'm not totally opposed to auto-formatting. I'm interested in what this would look like with CI, in particular, because a big issue at present is that one-off contributors are unlikely to format consistently. I frequently have to ask contributors to rebase to remove style changes unrelated to their actual contribution, and CI could probably help in that regard.

(As an aside, I am very surprised that your editor auto-formats all languages by default -- that would be a serious faux pas in my own work/language communities.)

**Comment by kennylevinsen** [comment]
> I'm interested in what this would look like with CI, in particular, because a big issue at present is that one-off contributors are unlikely to format consistently.

The general way I have previously enforced style checks is to run fmt in a check mode. For rustfmt through cargo, that would be done with `cargo fmt -- --check`, which fails if rustfmt would have modified the content.

For clarity, it can be added as a stage, making it more visible that its fmt that failed:

```yaml
jobs:
  include:
    - stage: rustfmt
      script: cargo fmt -- --check
    - stage: build
      script: cargo build
```
It could be made more advanced, but that would make it clear that green build requires rustfmt. Of course, a big-bang format would be required, but as the code-base isn't that large, I don't think it should be much of a problem. I also find such approach cleaner than progressive cleanup, as it would otherwise make PR's contain constant style changes.

> As an aside, I am very surprised that your editor auto-formats all languages by default

Some of my editor setups do, but it is my preferred configuration when possible. Most projects I work with require *fmt styles (gofmt, rustfmt, ...). I have strong opinions about consistency, and would not sleep well at night if I accidentally committed a stray newline. :)

Despite what one might think, it is actually quite rare that it ends up making stray modifications.

**Comment by JP-Ellis** [comment]
I very much agree with having a `rustfmt` check in the CI, especially given that the rustfmt is so well integrated in the Rust ecosystem (unlike what I have found in the C/C++ ecosystem).

It is true that this will introduce a barrier for one-time contributors; however, this is really quite small.  Most likely, they will have installed `rust` through `rustup`, in which case `rustfmt` is installed with:

```sh
rustup component add rustfmt
```

and once that is done, the only remaining barrier for these contributors is simply the need to run

```sh
cargo fmt
```

before they commit their changes.

**Comment by jheyens** [comment]
I think we should definitely find a solution here.
Disallowing `cargo fmt` has a hidden cost:
We need to explain this to new contributors and we probably annoy them by insisting on not using the autoformat tools.
PR #455 could have been a "Please run `cargo fmt`, thanks!" instead of mentioning non-functional changes for a simple two-line change.

I actually don't care a lot about "preserving git history on line changes" since you'll always be able to look at specific commits.
Using rustfmt with its default settings will allow us to use @kennylevinsen  proposed CI change and maybe even a bot saying "Hey, looks like you didn't run cargo fmt. Please run `cargo fmt` on your PR and submit a commit".

**Comment by atheriel** [comment]
> I actually don't care a lot about "preserving git history on line changes" since you'll always be able to look at specific commits.

I think you might have misunderstood. As a maintainer, I use `git blame` **all the time** to track down when changes were made to try and understand their original context, mostly so that fixing one bug does not eliminate an intended feature or re-introduce another bug. It becomes much harder to do this if the last change(s) were purely formatting, unless there is a feature of Git or GitHub that circumvents this that I am unaware of.

However, it is a compelling argument that formatting issues are a barrier to new contributors, which in truth matters more to me than `git blame`. It is also a much better argument than one for consistency or aesthetics. I think that carries the day, @jheyens. Thank you.

I am going to add the suggested CI changes by @kennylevinsen and then format the codebase in the near future.

It's worth noting that most -- if not all -- outstanding PRs will break when this happens. That's probably fine, because most of them need serious rebasing by their authors or by another volunteer anyway.

For any of you following this issue for a while, thank you for your patience.

**Comment by jheyens** [comment]
Thanks for making these changes.
Do you want to use rustfmt's default settings or are you going to create a rustfmt configuration file?
I'ld prefer the former, though I am not sure if the rustfmt developers may change its default behaviour in the future.

Additionally, have you heard of git blame's `--ignore-rev` flag? It's not a silver bullet for your issue of increased difficulty of tracking down changes, but it most definitely helps a lot.

**Comment by atheriel** [comment]
> Do you want to use rustfmt's default settings or are you going to create a rustfmt configuration file?

I reverted back to the defaults, yes.

> Additionally, have you heard of git blame's --ignore-rev flag?

I had not!
