### ISSUE TITLE
Pomodoro block

### ISSUE THREAD

**Issue by dharmit** [greshake/i3status-rust#372]
I just started using i3status-rust yesterday and I'm liking it so far. Thanks for putting it up!

Is there a plan to add pomodoro module to the project? For reference, [here's one in py3status's documentation](https://py3status.readthedocs.io/en/latest/modules.html#pomodoro). It's very helpful in reminding one to take breaks and avoid RSI.

**Comment by GladOSkar** [comment]
This is probably a good project for a beginner

**Comment by atheriel** [comment]
There have been a few other discussions of todo/time-tracker blocks (#195, #314). The response was lukewarm because they relied on the CLI of some external program, and in my view these programs just do not have enough mindshare to justify a bespoke block.

All this to say: I actually like the idea of a native implementation of pomodoro, as in the example you provided. We'd happily accept a PR. Although I will say that the configuration for py3status's implementation seems rather overcomplicated, and would advise a potential author to simplify...

**Comment by cosmoduff** [comment]
I recently created a pomodoro library as part of a rust learning project. It still needs a little work but I was able to create a basic pomodoro block using it. I would be willing to work on bringing it up to quality standards if there is interest. You can see the implementation I threw together [here](https://github.com/cosmoduff/i3status-rust/tree/pomodoro).

**Comment by ghedamat** [comment]
I completely missed this issue and ended up writing this 
https://github.com/greshake/i3status-rust/pull/453

**Comment by atheriel** [comment]
I believe @ghedamat's implementation is currently more promising than @cosmoduff's, because it avoids the `libpom` dependency.

**Comment by bruno-unna** [comment]
Hi guys,

I've recently updated to version `0.12.0-2` of `i3status-rust` and decided to give the _pomodoro_ block a try. It looks nice, thanks for the work!

That being said, I found strange that at the end of the first pomodoro, as I returned to my computer after a cup of coffee, the clock had been paused for the whole time my screen was locked.

Some additional experiments have led me to believe that the _block_'s clock always pauses when the screen is locked, regardless of whether this happens during the actual pomodoro or during the break.

Is this an expected behaviour? Should I file an issue?

Thanks in advance.

I'm running ArchLinux. Some information about my system:

```
singularity :: ~ % uname -a                                                                                                                                                                                         
Linux singularity 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux

singularity :: ~ % pacman -Qi i3status-rust                                                                                                                                                                         
Name            : i3status-rust
Version         : 0.12.0-2
...

singularity :: ~ % pacman -Qi i3-wm                                                                                                                                                                                 
Name            : i3-wm
Version         : 4.17.1-1
...

singularity :: ~ % pacman -Qi xscreensaver                                                                                                                                                                          
Name            : xscreensaver
Version         : 5.43-1
...

```

**Comment by atheriel** [comment]
@bruno-unna I believe this is a consequence of the fact that the current implementation does not use actual time but a tick system. We can probably fix this issue by using real timers instead. However, this should be filed as a separate issue.
