### ISSUE TITLE
Add Mocp support to music block

### ISSUE THREAD

**Issue by nicholasfagan** [greshake/i3status-rust#412]
Hey! Is there any interest in adding support for mocp to the music block? 
It does not support the current dbus interface.
I've already gone ahead and whippped up a working example [here](https://github.com/nicholasfagan/i3status-rust/tree/feature/mocp-music-block-support), and I'm willing to polish it up if there's interest.

**Comment by atheriel** [comment]
I took a look and I think the approach of adding an additional backend is interesting. However, I don't think this is the direction we want to move in quite yet, since there are quite a number of music players out there.

Instead, we are currently recommending (e.g. in #348 and #259) that you use a separate program to create a MPris2 D-Bus interface for your existing music player, which should then Just Work. A quick look around GitHub seems to indicate that there are several options. Is there a reason this would not be a good approach here?

**Comment by nicholasfagan** [comment]
I think the suggested approach (creating an MPris2 interface) will work for any scenario I can think of. 
My main reason for suggesting adding support is because I am new to rust and would love the practice! But heck, I can create the MPris2 interface in rust and that will be my practice. 
Thanks!
