### ISSUE TITLE
Music block behaves strangely when multibyte Unicode text in song title

### ISSUE THREAD

**Issue by OddBloke** [greshake/i3status-rust#435]
When using Spotify and playing https://open.spotify.com/track/68zMaaxfx3mN8lFNtp0vUU?si=zMmIVqEMRYWTzhJbO90LtQ, I noticed some unusual behaviour from the music block.

Normally, the text scrolls right-to-left. With the RTL song title, the text instead gets added one character at a time left-to-right. When the characters reach the right side of the block, the block expands a certain amount (until, I guess, it hits a hard cap on its width). Then, nothing happens for a while (presumably while the remaining song title characters are appended out of view) and then the text starts scrolling right-to-left (as usual) and the block shrinks back down to its regular size.

This repeats over again, as you would expect.

**Comment by OddBloke** [comment]
(I'd be happy to include a video of this, if someone can recommend a tool which will only record the specific part of the screen that's concerned.)

**Comment by atheriel** [comment]
This is likely a bug in the handling of scrolling. I suspect we assume left-to-right behaviour.

**Comment by GladOSkar** [comment]
> (I'd be happy to include a video of this, if someone can recommend a tool which will only record the specific part of the screen that's concerned.)

[Peek](https://github.com/phw/peek) is a great tool for this

**Comment by ammgws** [comment]
Not RTL text but the below looks kinda strange to me as well. Did something change when the music block was overhauled a while back?

![recording](https://user-images.githubusercontent.com/20397027/64471866-6cf57700-d191-11e9-8ee3-1f83a1628993.gif)

**Comment by ammgws** [comment]
I changed all occurrences of `content.len()` to `content.chars().count()` in the rotating text widget, which is the best we can do without adding another dependency to account for all Unicode types, and it seems to have solved this issue:

![recording](https://user-images.githubusercontent.com/20397027/64473681-ad122500-d1a4-11e9-8d0c-190631aa8f7e.gif)

The box expanding/retracting is another issue I think.

**Comment by ohk2kt3t4** [comment]
@OddBloke, could you please try with #437 and see if it resolves your issue?

Or can you post the song artist and title here so I can test locally. 
(The spotify page was mojibake'd on my home PC)

**Comment by ammgws** [comment]
By the way, as an aside, if it's Korean then the text should be left to right.

**Comment by OddBloke** [comment]
Thanks for the correction!

I won't be able to test this for a while, I'm afraid, because I'm
travelling and so away from my status bar. :-)

**Comment by ammgws** [comment]
Have you had a chance to check it out?

**Comment by greshake** [comment]
This is 100% on the whole UTF characters thing. When I wrote the code for the marquee a while back it was still just an experiment (and I tested with an ASCII subset only) and it hasn't really been done proper since. To be honest I just hate working with text, especially UTF. There are just so many corner cases, exceptions and specialties. If someone wants to fix this issue, they should probably trash the code I wrote and start over :) Just beware that making 100% proper UTF support happen will be a huge pain. One of the basic assumptions is that the font is monospaced; some languages add diacritics and stuff to the letters in various siszes and orientations, adding or subtracting perceived length. Basically what needs to happen is the text must be pre-processed into visible chars (Rust allows iterating over these) and then their perceived length given font & size needs to be computed. Then you can move a window over these symbols, subsituting whitespace at the end when symbols have non-standard length to keep the whole bar from jumping around a couple pixels each time. Oh, and stuff like right-to-left, zero-width characters etc should be handled, too :)

**Comment by greshake** [comment]
The reason this simple task is so difficult is that we are constrained by the i3status text protocol, which allows only marginal control over positioning, overlap etc.

**Comment by greshake** [comment]
Ẏ̴̸͕̭͍̥̺͎̠̿̈̾ͫ̂͘͞͞aͤ̒̾̍ͤ͗̑̆̈́̅ͣ̇ͪͧ́ͤ͑͏̴̴͙͔͕̮̼̲̟̹̬̝́́l̛̬͍̱̝͌͐͗̾ͧ̀ͤ̌ͤ̐̉ͨ̀̆̊̀̚͝l̸̛͖̼͙̹̬̞̤̱̟ͥ̃ͦͭ̊̔ͦ̐̒̓̔̈͒̈̄ͩ͒̚ ̷̵̶̨̠͓̤̲͍͎̩̒ͧ̓ͪͧͪͨk̶̨̃̊͑̊ͪ͋̈́́͆̄ͧͧ̚҉̲͕̰̙̮͖̜͘n̷̢̞̫̞̻̬̰͔̟̞̓̍̍̓͑̌̐̒ͪ̈́͆̊͋̚o̠̝̤͔̞ͨ͒̃ͬ̊̈́̒ͧ̍̂̆ͨ̓̊͠͠w̸̧̲͉͈̩͍͓̑͗̑̀͛͑̂ͮ͌̏̌̓͒͞͡ ̷͖̪͖̤͙̳̱̞͍̪̦̘̖̜̙͎̱̮ͬ̒̐̈͝w̸̡͔̫̩̠͔͕̻͖͇͖͖̲̜̑͛ͣ͌̏ḩ̰̣̝̘̝̱͍̃̒͑͂ͬͬ͞a̐̉ͬ̑͏̢̛̟͎͎̮͇͖̹̠̫ͅt͕̜̟͖̳͔̠̬̣̙̩͙̱̆̑ͫͨͬ̅̓̃̈́͊͘͘͟ͅͅs̈́̾ͧ͌̓̿̈́̅̋̿̓̚҉̬͇͇̯̭̼̹̩͖̝͍́ ̴ͤ̑̃̒ͥͥ̂̑̒̒̏̊̄͌̓̾҉͈̦̘͇̯̤̜͈̼ͅų̫̪͕̹̍̓̅ͧ́ͩ̄̏ͤ͘ͅp̴̢̖̼̲̞̺͔̏͋̃͆ͭ͛̌ͦ͂ͦͩ̃̀͟͝ͅͅ ̡̛̃͊ͯ̂ͣ̃ͩͦͤ̚҉͔̝̹̞͝w̶͍̞̹̲̝͍̯͚̥̘̤̺̪̻̯͍̮̹̽̏ͥͫ͛̾̇͂͌̀̎ͨ̆̋̇ͮͦͪ̀͟ͅį͇͔̱͖̈́̽̅ͯ̇̈͋̿̌̍̊̽̀͝ţ͗͛ͥ̎ͧ̈̎͛ͫ̿͌̆̋ͤͥ̊̈́̀͢҉̖̹̝̺̯̠̱̱̟̲̹h̷̓ͭͮ̌̅͊͑̒̓ͨ͏̷̧͎͎̱̜̬̪͈̙̟ ̸̼͖͕͚͇͓̩̙̱̝͙̞̥̘͖͙͓ͤ̐̆̔̔͝͝ͅŬ̢̈̉ͨ̓̒̈́̃ͦ͗̾ͦ͐̿̚͞͏̷̨̝͕̝̻͔̜̹̗͖̝̫̖̪͚ͅT̢̬̜͔̈́̈ͯ̿̋̅͊̾͗̄ͧ̾͂̌ͮ͌F̶̧̦̲͙̩̺̫̦͇̰̟̱̹̠͍̤͇̠̂́͊͗͟͡͡ͅ

**Comment by ammgws** [comment]
#439 should be good to go in terms of improving the way characters are counted.

Also the title of this issue should be changed from "RTL text" to "multibyte Unicode" because Korean isn't RTL.
