### ISSUE TITLE
Separator is broken on Sway

### ISSUE THREAD

**Issue by roipoussiere** [greshake/i3status-rust#466]
I'm using i3status-rust with sway, with this very simple bar config:

```
bar {
  position top
  separator_symbol .
  status_command i3status-rs $HOME/.config/i3status-rs/config.toml
}
```

But it displays, for each separator, an empty block surrounded by black blocks, instead of the `.`:

![2019-11-14_19-11-1573755548](https://user-images.githubusercontent.com/1665542/68884599-c76ffe00-0713-11ea-8e96-42368cc35fb6.jpg)

This glitch disappear when I comment the `separator_symbol` option.
I used i3status before to switch to i3status-rust and this issue was not present.

The rust config file is almost the same as [the example config file](https://raw.githubusercontent.com/greshake/i3status-rust/master/example_config.toml).

- **i3status-rs --version**: `i3status-rs 0.11.0`
- **sway --version**: `sway version 1.2`

**Comment by atheriel** [comment]
This is expected behaviour under the i3bar protocol (unless this looks different on `i3` than `sway`).

To clarify, what is happening here is that `i3status-rust` implements its own separator symbols by inserting them as additional blocks in the bar. When you use `sway`'s native separators, these are inserted between each block, including the separator blocks, causing the pattern you observe. That is why, for example, the blocks and separators have different values from your `sway` colour configuration.

You probably want to set `theme.separator = "."` in your `i3status-rust` config and remove the `separator_symbol` from your `sway` config.

**Comment by roipoussiere** [comment]
Thank you! This fixed it.
