### ISSUE TITLE
Add flag to suppress errors on startup

### ISSUE THREAD

**Issue by michelboaventura** [greshake/i3status-rust#50]
I use i3status-rs on both my pc and notebook, sharing the same configuration. But since only the notebook has a battery, the configuration doesn't work on my PC and I have to always comment the battery block.

It would be great if we have a flag to just ignore any block with errors, but show the other ones.

**Comment by greshake** [comment]
I don't really like the proposed solution, seems hacky and might lead to confusion down the road (issues being openend because error messages are hidden because someone only copy-pasted the config/cmd line args). Also it would just make sense to have separate configs in your use case. But I'll await further judgement from others, maybe there is more demand for this feature than I estimate.

**Comment by greshake** [comment]
@jheyens @pitkley @keeslinp @svmnotn Any comment?

**Comment by michelboaventura** [comment]
I understand your point, and maybe I'm the only one sharing the same i3status-rs/i3/entire world of configs between my pcs :)

**Comment by svmnotn** [comment]
Maybe have all blocks have an `optional = false` tag that can be changed to _true_.
That way if the block is optional, any errors will simply cause the block to not be displayed?
That seems like a more complete solution, specially if all blocks default to _false_ so that users would have to opt-in to the feature.

**Comment by keeslinp** [comment]
I think one helpful thing would a message saying which module failed. Are we currently displaying any information with the error message? I'm running a pretty old version so I'm not sure. When I first tried out this app I had to just comment out stuff until it worked and go from there.

**Comment by keeslinp** [comment]
I agree that silently failing is probably a bad idea. I haven't updated in a while so I'm not sure about how it's all handled at the moment. I'll try to test some things out this weekend if I get the time (It's been pretty crazy lately) and I'll try to have a more informed opinion.

Two very early thoughts are this:
1. I like the idea of an optional flag that defaults to fail explicitly because it allows people to have more seamless usage across devices without messing with the average user.
2. If we can contain failure to an individual component it could add buttons to a dead component to either restart or hide it. That also helps with one-off errors so people don't have to restart all of i3 to get it back up.

**Comment by svmnotn** [comment]
@keeslinp I like the idea that
> If we can contain failure to an individual component it could add buttons to a dead component to either restart or hide it. That also helps with one-off errors so people don't have to restart all of i3 to get it back up.

Now that we have most things return a `Result<_>` it should be possible to do, but that should probably be its own issue.

**Comment by jheyens** [comment]
I definitely would not like to have a global mute switch for all blocks simultaneously. 
I am not even sure if I would like an `optional` switch for all blocks, because there are some, where it doesn't make a lot of sense.
The time block for example (or memory, CPU, LOAD) has zero external dependencies and if that one stops working for some reason, the user shall have to manually interact with the configuration and file an issue.

We could have each block get an `optional´ switch by default with the possibility  of an override in a block implementation. But then again, this probably isn't even the trouble and we should just give every block that switch by default.

**Comment by greshake** [comment]
I have a different suggestion to resolving this issue; Instead of suppressing failing blocks, we could intrpduce 'profiles' or blacklists that trigger on a command line argument:

```toml
[[profile]]
trigger = "desktop" # triggered by the desktop command line arg
blacklist = ["battery"]
```

If the use-case also uses shared i3conf's we're obviously only shifting the problem. But, you could have something like this in your i3 config as command:
`status_command bash -c 'i3status-rs $(cat ~/.is_desktop) status.toml'`

By having the .is_desktop file with the trigger as contents in the home directory of the desktop, you can trigger the profile. However we do it, profiles would be a more elegant and flexible solution. But my draft needs polishing :)

**Comment by jlesquembre** [comment]
I'm also sharing the configuration between multiple computers and was bitten by this issue.

I have another suggestion, what do you think about adding a tag for all blocks for a test command? E.g.:

```toml
[[block]]
block = "battery"
if_command = "upower -e"
```

If the command `upower -e` exits with an error code, the block will not be rendered.

**Comment by greshake** [comment]
I like the idea

**Comment by Fuzen-py** [comment]
Would like to see this implemented as well, the only time I have the battery block is when I'm using a Bluetooth keyboard, this means that this block fails if at any time the keyboard isn't connected. I think setting a block as optional is a good idea.

**Comment by ammgws** [comment]
I believe the most common issues with respect to batteries and network devices are now non-issues due to the various`allow_missing`, `hide_missing` options that were added to those blocks.
