### ISSUE TITLE
time does not update after stand-by until next minute

### ISSUE THREAD

**Issue by rubdos** [greshake/i3status-rust#66]
See title; I just came back from standby, noticing it took a long time until the time was displayed correctly. I suppose this was because the asynchronous event didn't trigger until the next minute.

**Comment by greshake** [comment]
Well, the time block updates in a specified interval, by default every 5 seconds. In my configuration, I have the interval set to one minute, because I don't display seconds so this is accurate enough for me. In general, no part of the program is currently aware of being suspended and everything uses relative time (e.g. Duration to the next update). If you've set it to one minute and go to standby right after an update, the next update will obviously occur one minute after being woken up again. There are a few things we could do here:
* If this is a big issue for you, just set the update interval of the time block higher, updating it is very cheap.
* We can try to detect standy-wakeup cycles and schedule immediate updates for all blocks after wakeup. This, however, might break blocks that assume updates will only be triggered by their own code. 
* We can convert all relative update times (durations) to absolute time, so if the computer has been set to sleep and wakes up hours later, all updates will be executed immediately because they have been scheduled to a past time.

For now, use the first option. I'll think about implementing the third option, but I will still have to give this some thought before implementing. You can try to make a PR if this is a very pressing issue for you :)

**Comment by rubdos** [comment]
Oh, it's not a pressing issue for me. It's just something "nice to have". The battery thing is more pressing :D

Thanks for giving it thought. If you give it some thought, feel free to let me know. I'd love to implement it; just not today, nor next week. I'll be in Zürich the first weeks of august, I'll probably have some time then.

**Comment by greshake** [comment]
Okay, I forgot the way it's already implemented. We are already using absolute times in the scheduler. The reason it doesn't update for you is probably that the schedule isn't being updated, because you must have no short-period updating blocks... Anyway, I've given this some thought and there is no elegant way to improve here.... Just adjust the update interval of the time block. I've just abolished busy wait in main() and I don't see a good way of checking for wake ups asynchronously so that is pretty much a nofix for now.

**Comment by rubdos** [comment]
If you say "for now", would you mind keeping this open, or me reopening this in a few weeks? It's yours to decide though :)

**Comment by greshake** [comment]
If you have a suggestion we may keep this open for later implementation- All the things I suggested will either not work or introduce severe overhead.

**Comment by rubdos** [comment]
I see. I just feel a bit weird about a wontfix bug so early on.

Would it be possible to subscribe to some kernel event, perhaps?

**Comment by WGH-** [comment]
It's quite possible to fix it efficiently. See https://github.com/soumya92/barista/issues/150 https://github.com/soumya92/barista/pull/152
