### ISSUE TITLE
[Med Prio] Change architecture to support more output formats

### ISSUE THREAD

**Issue by greshake** [greshake/i3status-rust#7]
Because i3status-rust is already using an abstract representation for UI elements (widgets) it shouldn't be too much effore to abstract away from the i3bar protocol, to support other bars like dzen2.

**Comment by svmnotn** [comment]
Would we do that as a feature flag, or as a cli option? This should probably be easy to do by altering the `print_blocks` function. Perhaps making a special trait that knows how to print blocks to the specific bar, and then just implementing the trait on an empty struct so that we can select the right impl at runtime; or just select the right impl at compile time.

**Comment by greshake** [comment]
Hmm the first thing I think we need to do is research how other bar protocols work... If it's always just printing somehting to stdout, it should be easy... But even then, there is trouble. Currently, the widgets cache a rendered version of themselves, which is obviously dependent on the output format. There is some consideration and work to come if we are going to support other bars.

**Comment by ammgws** [comment]
Doesn't look like there is any demand for this.
