### ISSUE TITLE
Temperature block displays with 15 decimal places

### ISSUE THREAD

**Issue by kflak** [greshake/i3status-rust#815]
As of today I am getting a 15 decimal place display of my computer's temperature... Not quite needed. Is there a way to format this as an integer?

System: Arch Linux, 5.4.58-rt35-2-rt-lts, sway v1.5, i3status-rs 0.14.1

**Comment by ammgws** [comment]
Until something like #724 / #750 is implemented then there's no way to fix this right now without amending the code itself.

**Comment by ammgws** [comment]
Is the temperature itself correct or is it over/underflowing?

**Comment by kflak** [comment]
Seems like it is reporting the correct temperature. In the meantime I discovered the `collapsed = true` parameter which basically gives me all the information that I need. Sometimes the only precision I need is a friendly color code... :-D

**Comment by ammgws** [comment]
I'm guessing you're running git master and this only came up after https://github.com/greshake/i3status-rust/pull/811 ?

**Comment by kflak** [comment]
So it seems. Not able to confirm 100% right now, but I'm pulling from aur i3status-rust-git, so should be the latest master.

**Comment by arraypad** [comment]
@ammgws I changed it to a float because I appreciate the precision but for my chip `sensors` is returning a more sensible precision - I've only ever seen at most once digit after the decimal place. Sorry this issue didn't occur to me!

I don't think more than one decimal place is very useful so it would be good to fix, but with #750 on the horizon I'm not sure if this is worthwhile to fix individually. Maybe round to 1 decimal place for now?

**Comment by ammgws** [comment]
I'll revert the type back to `int` for now.
