### ISSUE TITLE
Improve network block

### ISSUE THREAD

**Issue by dakra** [greshake/i3status-rust#82]
It would be nice to have more display options for the "net" block.
For example I would just like to show the interface IP instead of the current
bandwith.

Also an option to hide (or a different text) the block if the interface is down.

Something like (from my old config):

```
ethernet tun0 {
        format_up = "VPN: %ip"
        format_down = "VPN: down"
}
ethernet net0 {
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}
ethernet net1 {
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}
```

Instead of 'E: down' I would actually prefer to only show the
active interface (not possible with i3status).

Nice status bar. Thanks :)

**Comment by greshake** [comment]
@etrombly did the net block, maybe he wants to help you out :)

**Comment by etrombly** [comment]
Shouldn't be too hard to add the ip. I didn't add it originally because there isn't a standard for formatting across blocks, it's handled at the block level, so I was waiting to see if anything was created for that. @greshake if I send an empty vec back for the view function will the block not be drawn at all? If not I can just change the status.

**Comment by greshake** [comment]
Correct, it will not be displayed.
See util.rs:99:
```rust
        if widgets.len() == 0 {
            continue;
        }
```

**Comment by atheriel** [comment]
@greshake @etrombly Any objection to my upstreaming some related changes to the Net block? It would add these features.

**Comment by etrombly** [comment]
I don't have a problem with it. Anything to improve it is welcome.

**Comment by greshake** [comment]
Sure go ahead
