### ISSUE TITLE
Conditional display of blocks

### ISSUE THREAD

**Issue by bascht** [greshake/i3status-rust#837]
Hi @greshake. I hope it's okay if I open up an issue for a request, but I couldn't find anything in the code, docs, or other related issues:

I would like i3status-rs to have some kind of conditional functionality that would let me show / hide different blocks based on their value / status, e.g.

- only display the *load block* if load is > 2
- hide the battery block if the battery is fully charged

I know some blocks provide that functionality but I think it would be a great addition to i3status-rs itself. Would you consider this a feature?

**Comment by Brod8362** [comment]
I think these features would be best implements on a per-block level as opposed to a universal switch. The battery block already collapses when it's fully charged, but the load block does not have a similar option. If you know a bit of rust, it wouldn't be too difficult to jump in an add them yourself.

Regardless, I do think the load block could do with a bit more customization, although "load > 2" is pretty unclear since it could be 1m, 5m, or 15m load.

**Comment by bascht** [comment]
@Brod8362 You might be right. Thanks for the extensive answer! I just scrolled through #847 and this looks way easier than I thought. Maybe I get to write some rust after all… :D 

You can close this issue at will! :raised_hands:

**Comment by Seirdy** [comment]
Yeah, conditional display is great; +1 on that.

> I think these features would be best implemented on a per-block level as opposed to a universal switch.

@Brod8362 I see where you’re coming from; however, there exist way too many possible use-cases and conditionals to bake into i3status-rust. Some examples:

- Only display some blocks on hostnames matching a regex. My desktop doesn’t need to display battery status or disk usage (since it has a big disk).
- Complex battery conditionals:
  - If this computer is my laptop with the main battery, display the battery block if:
    - connected to AC *and* when the battery is above 50%, *or*:
    - when the battery is above 80% and discharging
  - If this computer is my laptop with a small spare battery, always display the battery block
- Only display the mail block for my work inbox during working hours.
- If my screen is small, save space by only displaying my UTC time block if the music block isn’t also displayed.

Most people are part of a unique edge case, but implementing each unique edge would take hundreds of hours and make i3status-rs 10x more complex.

The two easiest ways to handle this:

1.  Provide a mechanism for re-sourcing the configs, or document a simple way to restart i3status-rs without a nuclear option like reloading sway/i3 (reloading sway takes 5 seconds of full CPU utilization on my 2013 Elitebook). That way, other user-made scripts can alter the i3status-rs configs for specific edge-cases.
2.  To address conditions that rarely/never change, each block can run a user-configurable program. If that program has an exit status of anything besides 0, don’t display the block.

**Comment by Brod8362** [comment]
> I see where you’re coming from; however, there exist way too many possible use-cases and conditionals to bake into i3status-rust

@Seirdy I definitely agree. I like the idea of having it run a user-configurable program, though that brings up the question of how exactly the information would be passed into it.

I *especially* like the "only show if host matches regex" idea, or having external programs able to send signals to hide/show certain blocks. Would be great for docked laptops, allowing you to hide/show what's necessary when its operating as a "desktop"

**Comment by ammgws** [comment]
Some previous discussion relevant to point 2 above
https://github.com/greshake/i3status-rust/issues/50#issuecomment-362104891

**Comment by ammgws** [comment]
`if_command` covers this for first startup of i3status-rs, and as far as I can see anything else can only be done on a per-block basis, if at all.
