### ISSUE TITLE
Font doesn't look right

### ISSUE THREAD

**Issue by Nobabs27** [greshake/i3status-rust#94]
Following an update:
http://imgur.com/a/kx8mo

Any fix to the detached triangle character things?

**Comment by greshake** [comment]
Had that issue, too. Fiddling with the font size helped... In any case, it's not something we can take influence on with the i3bar protocol. Go look over there (i3bar) if you still can't fix it :)

**Comment by Nobabs27** [comment]
Setting font size to 7.9 seemed to fix it, thanks!

**Comment by GladOSkar** [comment]
i3 adds padding around the text, that is why the arrows don't take the full height.

If it is really important to you, you can recompile i3 with this patch (made by the infamous Airblader):
https://gist.github.com/Airblader/72d6a03d05c111d33ad4

**Comment by GladOSkar** [comment]
Fiddling with the font size did not work for me.

OK i finally got around to looking at this again and did some research on my own

The problem is the following: Above the top and below the baseline of the text, 3 logical pixels are added by i3 because it looks better. Unfortunately, we do not want this behavior to occur with the powerline sparators.

So i wrote this patch for the pango text rendering in i3 which just renders the powerline characters bigger and moves them to the right spot.

This is very hacky, may not work on other resolutions and has the font hardcoded, but it's something, in case someone is still searching:

https://gist.github.com/GladOSkar/408d3722be33f1a6da18950a9db83bf3

Now i have perfect edges:

![image](https://user-images.githubusercontent.com/9497832/43223636-059df9f8-9054-11e8-8d5e-4bb470d8bca3.png)

**Comment by atheriel** [comment]
@GladOSkar that's a very nice reference experiment to have on hand!
