### ISSUE TITLE
net block: default device change during runtime

### ISSUE THREAD

**Issue by marzzzello** [greshake/i3status-rust#987]
The current implementation of the net block doesn't update the default device at the interval update, only at the start of the bar.

Current config:
```toml
[[block]]
block = "net"
interval = 1
```
To reproduce
1. connect to ethernet, turn wifi off:
-> bar shows ethernet
`ip route show default`: ethernet device
2. connect to wifi, disconnect ethernet:
-> bar shows ethernet as disconnected
`ip route show default`: wifi device
3. restart i3:
-> bar shows wifi
`ip route show default`: wifi device

Related: #626

**Comment by ammgws** [comment]
OK so it looks like you need `auto_device = true` in your config for this to work (https://github.com/greshake/i3status-rust/blob/9529d72b2e3285f0d185e7c5924e71310c378e90/src/blocks/net.rs#L744), however it has been undocumented this whole time. I think I will change it so that it will do this default device auto-discovery whenever `device` has not been set in the config.

However I think there may be another issue here - it falls back to `"lo"` if there is no default device found (for example if you take down both your ethernet and wireless links), but this seems kind of useless and the loopback device shows as a connected ethernet device in the bar which is misleading.

**Comment by marzzzello** [comment]
Yes `auto_device = true` works fine. 
I agree that the fallback to the loopback device is misleading and unnecessary.
